import { MEDIA_MESSAGE } from '@extension/shared';
import type { SubtitleTrack } from '@extension/shared';
import { createBridge, onFromMain, sendToMain } from '@src/lib/broadcast-bridge';

const sentUrls = new Set<string>();

type YTFormat = {
  url?: string;
  signatureCipher?: string;
  mimeType?: string;
  qualityLabel?: string;
  width?: number;
  height?: number;
  contentLength?: string;
  audioQuality?: string;
  bitrate?: number;
};

type StreamingData = {
  formats?: YTFormat[];
  adaptiveFormats?: YTFormat[];
  hlsManifestUrl?: string;
  dashManifestUrl?: string;
};

type YTCaptionTrack = {
  baseUrl?: string;
  languageCode?: string;
  kind?: string; // 'asr' for auto-generated
  name?: { simpleText?: string };
  vssId?: string;
};

type PlayerResponse = {
  streamingData?: StreamingData;
  videoDetails?: { title?: string; lengthSeconds?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YTCaptionTrack[];
    };
  };
};

const extractCaptionTracks = (pr: PlayerResponse): SubtitleTrack[] => {
  const tracks = pr.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const out: SubtitleTrack[] = [];
  for (const t of tracks) {
    if (!t.baseUrl || !t.languageCode) continue;
    // Request WebVTT explicitly — YouTube's default format is timedtext XML.
    const url = new URL(t.baseUrl);
    url.searchParams.set('fmt', 'vtt');
    out.push({
      url: url.toString(),
      language: t.languageCode,
      label: t.name?.simpleText,
      format: 'vtt',
      isAutoGenerated: t.kind === 'asr',
    });
  }
  return out;
};

const sendCandidate = (candidate: {
  url: string;
  kind: 'video' | 'audio' | 'hls' | 'dash';
  mimeType?: string;
  title?: string;
  resolution?: { width: number; height: number };
  contentLength?: number;
  audioUrl?: string;
  audioMimeType?: string;
  subtitles?: SubtitleTrack[];
}) => {
  if (!candidate.url || sentUrls.has(candidate.url)) return;
  sentUrls.add(candidate.url);
  chrome.runtime
    .sendMessage({
      type: MEDIA_MESSAGE.DETECTED,
      payload: {
        url: candidate.url,
        mimeType: candidate.mimeType,
        kind: candidate.kind,
        source: 'element' as const,
        title: candidate.title ?? document.title.replace(/\s*-\s*YouTube$/, ''),
        audioUrl: candidate.audioUrl,
        audioMimeType: candidate.audioMimeType,
        subtitles: candidate.subtitles,
      },
    })
    .catch(() => undefined);
};

const extractFormats = (pr: PlayerResponse) => {
  const { streamingData, videoDetails } = pr;
  if (!streamingData) return;

  const rawTitle = videoDetails?.title ?? document.title;
  const title = rawTitle.replace(/\s*-\s*YouTube$/, '');
  const subtitles = extractCaptionTracks(pr);
  const subs = subtitles.length > 0 ? subtitles : undefined;

  // Live / HLS stream
  if (streamingData.hlsManifestUrl) {
    sendCandidate({ url: streamingData.hlsManifestUrl, kind: 'hls', title, subtitles: subs });
  }

  // DASH manifest
  if (streamingData.dashManifestUrl) {
    sendCandidate({ url: streamingData.dashManifestUrl, kind: 'dash', title, subtitles: subs });
  }

  // Combined audio+video formats (itags 18, 22, etc.) — always prefer these for simplicity
  for (const fmt of streamingData.formats ?? []) {
    if (!fmt.url) continue; // signatureCipher — cannot use without JS decipher
    const kind = fmt.mimeType?.startsWith('audio/') ? 'audio' : 'video';
    sendCandidate({
      url: fmt.url,
      kind: kind as 'video' | 'audio',
      mimeType: fmt.mimeType,
      title: fmt.qualityLabel ? `${title} [${fmt.qualityLabel}]` : title,
      resolution: fmt.width && fmt.height ? { width: fmt.width, height: fmt.height } : undefined,
      contentLength: fmt.contentLength ? Number(fmt.contentLength) : undefined,
      subtitles: kind === 'video' ? subs : undefined,
    });
  }

  // Adaptive formats: video-only streams must be paired with an audio-only stream
  // and muxed. We only advertise AVC (video/mp4) + AAC (audio/mp4) combinations
  // so the downloader can stream-copy into an MP4 container without re-encoding.
  const adaptive = (streamingData.adaptiveFormats ?? []).filter(f => !!f.url);
  const videoOnly = adaptive.filter(f => f.mimeType?.startsWith('video/mp4'));
  const audioOnly = adaptive.filter(f => f.mimeType?.startsWith('audio/mp4'));

  // Pick the highest-bitrate AAC audio as the universal pair
  const bestAudio = audioOnly.sort((a, b) => (b.bitrate ?? 0) - (a.bitrate ?? 0))[0];

  for (const fmt of videoOnly) {
    sendCandidate({
      url: fmt.url!,
      kind: 'video',
      mimeType: fmt.mimeType,
      title: `${title} [${fmt.qualityLabel ?? `${fmt.height}p`}]`,
      resolution: fmt.width && fmt.height ? { width: fmt.width, height: fmt.height } : undefined,
      contentLength: fmt.contentLength ? Number(fmt.contentLength) : undefined,
      audioUrl: bestAudio?.url,
      audioMimeType: bestAudio?.mimeType,
      subtitles: subs,
    });
  }

  // Also expose the best audio stream on its own so users can grab just audio
  if (bestAudio?.url) {
    sendCandidate({
      url: bestAudio.url,
      kind: 'audio',
      mimeType: bestAudio.mimeType,
      title: `${title} [${bestAudio.audioQuality ?? 'audio'}]`,
      contentLength: bestAudio.contentLength ? Number(bestAudio.contentLength) : undefined,
    });
  }
};

/* ── Script-tag fallback (when MAIN world relay isn't ready yet) ── */
const extractFromScriptTag = (): boolean => {
  for (const script of Array.from(document.querySelectorAll('script'))) {
    const text = script.textContent ?? '';
    // Try both assignment forms YouTube uses
    const match =
      text.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\})(?:;|,|\n)/s) ??
      text.match(/ytInitialPlayerResponse":\s*(\{.+?\})(?:,|\})/s);
    if (match?.[1]) {
      try {
        const pr = JSON.parse(match[1]) as PlayerResponse;
        if (pr?.streamingData) {
          extractFormats(pr);
          return true;
        }
      } catch {
        continue;
      }
    }
  }
  return false;
};

let mainWorldRelayReceived = false;

/* ── BroadcastChannel bridge ── */
const bridge = createBridge(window.location.href);

onFromMain(bridge, msg => {
  if (msg.name === 'youtube_on_visitor_data') {
    // VISITOR_DATA reserved for future authenticated API requests — no action needed yet
  }

  if (msg.name === 'youtube_player_response') {
    const pr = (msg.data as { playerResponse?: PlayerResponse })?.playerResponse;
    if (pr?.streamingData) {
      mainWorldRelayReceived = true;
      extractFormats(pr);
    }
  }
});

sendToMain(bridge, { name: 'youtube_request_visitor_data', data: null });
sendToMain(bridge, { name: 'youtube_request_player_response', data: null });

/* ── Initial extraction ── */
const tryExtract = () => {
  sendToMain(bridge, { name: 'youtube_request_player_response', data: null });
  // Give the MAIN world 300 ms to reply; fall back to script-tag parsing if it doesn't
  setTimeout(() => {
    if (!mainWorldRelayReceived) extractFromScriptTag();
  }, 300);
};

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => setTimeout(tryExtract, 800));
} else {
  setTimeout(tryExtract, 800);
}

/* ── SPA navigation ── */
document.addEventListener('yt-navigate-finish', () => {
  sentUrls.clear();
  mainWorldRelayReceived = false;
  setTimeout(tryExtract, 1200);
});

let lastUrl = location.href;
new MutationObserver(() => {
  if (location.href !== lastUrl) {
    lastUrl = location.href;
    sentUrls.clear();
    mainWorldRelayReceived = false;
    setTimeout(tryExtract, 1200);
  }
}).observe(document.documentElement, { childList: true, subtree: true });
