import { createStorage, StorageEnum } from '../base/index.js';

// Local copies to avoid depending on @extension/shared and introducing a cycle
type MediaKind = 'video' | 'audio' | 'hls' | 'dash' | 'subtitle' | 'other';
type MediaSource = 'element' | 'network';
type SubtitleFormat = 'vtt' | 'srt' | 'ttml' | 'xml';
type SubtitleTrack = {
  url: string;
  language: string;
  label?: string;
  format: SubtitleFormat;
  isAutoGenerated?: boolean;
};
type MediaVariant = {
  url: string;
  name?: string;
  bandwidth?: number;
  resolution?: { width: number; height: number };
  codecs?: string;
  audioUrl?: string;
  audioMimeType?: string;
  isDrmProtected?: boolean;
};
type MediaItem = {
  id: string;
  url: string;
  kind: MediaKind;
  mimeType?: string;
  title?: string;
  pageUrl?: string;
  tabId?: number;
  detectedAt: number;
  source: MediaSource;
  fileName?: string;
  contentLength?: number;
  variants?: MediaVariant[];
  thumbnail?: string;
  duration?: number;
  audioUrl?: string;
  audioMimeType?: string;
  subtitles?: SubtitleTrack[];
  isDrmProtected?: boolean;
};
type MediaDownloadStage =
  | 'init'
  | 'fetch-manifest'
  | 'download-video'
  | 'download-audio'
  | 'mux'
  | 'finalize'
  | 'success'
  | 'failed'
  | 'cancelled'
  | 'paused';
type MediaDownloadProgress = {
  key: string;
  stage: MediaDownloadStage;
  downloadedBytes: number;
  estimatedBytes?: number;
  muxPercent?: number;
  error?: string;
  downloadId?: number;
  item?: MediaItem;
  outputFormat?: 'mp4' | 'mp3';
  startedAt?: number;
  updatedAt?: number;
};
type MediaDownloadState = Record<string, MediaDownloadProgress>;
type MediaHistoryItem = MediaItem & {
  downloadedAt: number;
  status: 'success' | 'failed';
  failureReason?: string;
};
type MediaDetectionState = Record<string, MediaItem[]>;
type MediaHistoryState = MediaHistoryItem[];
type MediaSettings = {
  enableHlsMerging: boolean;
  maxHistory: number;
  filenameTemplate: string;
  // Max concurrent downloads through the queue. Default 1 — libav HLS/DASH
  // muxes are RAM- and OPFS-bandwidth-heavy and running two simultaneously
  // degrades both. Users with headroom can bump this from the options page.
  downloadConcurrency: number;
  // Intercept browser-initiated video/audio downloads and offer to handle them
  // through Vidsy. Default ON — the modal lets the user choose "Open in
  // Browser" per-download, and there's a settings toggle to disable entirely.
  enableDownloadInterceptor: boolean;
  // Number of parallel HTTP Range connections per single download. Default 8.
  // Higher values can speed up downloads on Range-capable CDNs but hammer the
  // server; lower values are friendlier on flaky links. Clamped at runtime
  // to [1, 16].
  downloadConnectionsPerFile: number;
};

const DEFAULT_MEDIA_SETTINGS: MediaSettings = {
  enableHlsMerging: true,
  maxHistory: 30,
  filenameTemplate: '',
  downloadConcurrency: 1,
  enableDownloadInterceptor: true,
  downloadConnectionsPerFile: 8,
};

export const mediaDetectionsStorage = createStorage<MediaDetectionState>(
  'media-detections',
  {},
  {
    storageEnum: StorageEnum.Session,
    liveUpdate: true,
    sessionAccessForContentScripts: true,
  },
);

export const mediaHistoryStorage = createStorage<MediaHistoryState>('media-history', [], {
  storageEnum: StorageEnum.Local,
  liveUpdate: true,
});

export const mediaSettingsStorage = createStorage<MediaSettings>('media-settings', DEFAULT_MEDIA_SETTINGS, {
  storageEnum: StorageEnum.Local,
  liveUpdate: true,
});

export const mediaDownloadsStorage = createStorage<MediaDownloadState>(
  'media-downloads',
  {},
  {
    storageEnum: StorageEnum.Session,
    liveUpdate: true,
    sessionAccessForContentScripts: true,
  },
);
