export type MediaKind = 'video' | 'audio' | 'hls' | 'dash' | 'mss' | 'mse' | 'subtitle' | 'other';
export type MediaSource = 'element' | 'network';

export type SubtitleFormat = 'vtt' | 'srt' | 'ttml' | 'xml';

export type SubtitleTrack = {
  url: string;
  language: string; // BCP-47ish: 'en', 'es-419', 'pt-BR'
  label?: string; // human-readable: 'English', 'Spanish (Latin America)'
  format: SubtitleFormat;
  isAutoGenerated?: boolean;
};

export type MediaVariant = {
  url: string;
  name?: string;
  bandwidth?: number;
  resolution?: { width: number; height: number };
  // Exact size in bytes. Set when the variant is an HTTP file whose
  // Content-Length we learned via HEAD or a network response. Absent for
  // HLS/DASH segments (use bandwidth × duration for an estimate).
  contentLength?: number;
  codecs?: string;
  // Set when this variant is video-only and must be muxed with a separate audio track.
  // The downloader fetches both streams in parallel and merges them via FFmpeg -c copy.
  audioUrl?: string;
  audioMimeType?: string;
  // True when the manifest declared DRM key systems (Widevine/PlayReady/FairPlay).
  // The downloader cannot decrypt these streams — the UI disables the action.
  isDrmProtected?: boolean;
};

export type MediaItem = {
  id: string;
  url: string;
  kind: MediaKind;
  mimeType?: string;
  title?: string;
  pageUrl?: string;
  tabId?: number;
  detectedAt: number;
  source: MediaSource;
  fileName?: string;
  contentLength?: number;
  variants?: MediaVariant[];
  // Native resolution of the rendered <video> element (or top-level stream
  // when known). Drives the "1080p" badge on rows without per-variant data.
  resolution?: { width: number; height: number };
  thumbnail?: string; // data URL or poster URL
  duration?: number; // seconds
  // Top-level audio pairing — used when the item itself (not a variant) is a
  // video-only stream that should be muxed with a separate audio track.
  audioUrl?: string;
  audioMimeType?: string;
  // Sidecar subtitle tracks attached to this video (YouTube captions, HLS/DASH text tracks).
  // Rendered as a language picker in the "More" menu.
  subtitles?: SubtitleTrack[];
  // True when any variant of this HLS/DASH manifest declared a DRM key system.
  // The downloader is intentionally DRM-blind — this flag just drives the UI lockout.
  isDrmProtected?: boolean;
  // True when this is a live HLS stream (media playlist with no #EXT-X-ENDLIST).
  // Drives the Record action in the UI. May be undefined until liveness is known
  // — the recorder re-validates at start, so the flag is a hint, not a gate.
  isLive?: boolean;
};

export type MediaDownloadStage =
  | 'queued'
  | 'init'
  | 'fetch-manifest'
  | 'recording'
  | 'recording-paused'
  | 'download-video'
  | 'download-audio'
  | 'mux'
  | 'finalize'
  | 'success'
  | 'failed'
  | 'cancelled'
  | 'paused';

// Per-connection chunk progress for HTTP Range parallel downloads. Reported by
// the worker so the details window can render a multi-band position bar and
// table similar to the connections breakdown in dedicated download managers.
// Only populated for HTTP-range downloads; HLS/DASH segment fetches leave it
// unset since the visualization doesn't translate to many small segments.
export type ChunkProgress = {
  i: number; // 0-based chunk index
  start: number; // inclusive byte offset in the destination file
  end: number; // inclusive byte offset in the destination file
  // Bytes downloaded so far for this chunk — updated live as the HTTP body
  // streams in, so the UI can render per-connection throughput / fill state.
  // For status === 'done' this equals (end - start + 1); for 'pending' it is 0.
  downloaded: number;
  status: 'pending' | 'fetching' | 'done' | 'error';
};

export type MediaDownloadProgress = {
  key: string; // typically url
  stage: MediaDownloadStage;
  downloadedBytes: number;
  estimatedBytes?: number;
  muxPercent?: number;
  error?: string;
  downloadId?: number; // chrome.downloads ID for Play / Show in Folder
  item?: MediaItem; // snapshot of the source item — powers the Downloads tab and Retry
  outputFormat?: 'mp4' | 'mp3'; // remembered so Retry reuses the original choice
  startedAt?: number;
  updatedAt?: number;
  queuePosition?: number; // 1-based, shown when stage === 'queued'
  chunks?: ChunkProgress[]; // per-connection breakdown (HTTP range only)
};

export type MediaDownloadState = Record<string, MediaDownloadProgress>;

export type MediaHistoryItem = MediaItem & {
  downloadedAt: number;
  status: 'success' | 'failed';
  failureReason?: string;
  downloadId?: number; // chrome.downloads ID — used for Play / Show in Folder
};

export type MediaDetectionState = Record<string, MediaItem[]>;
export type MediaHistoryState = MediaHistoryItem[];

// Resume manifest persisted in chrome.storage.local on pause so an HTTP-range
// download can be resumed in a different browser session. Mirrored from the
// session-scoped mediaDownloadsStorage entry; lifetime is bounded by
// MediaSettings.pausedDownloadRetentionDays, after which the offscreen-doc
// startup GC sweeps both the manifest and the underlying OPFS file.
export type ResumeManifest = {
  key: string;
  url: string;
  fileName?: string;
  title?: string;
  item: MediaItem;
  outputFormat?: 'mp4' | 'mp3';
  opfsName: string;
  totalBytes: number;
  ranges: { start: number; end: number }[];
  chunks: ChunkProgress[];
  downloadedBytes: number;
  pausedAt: number;
  expiresAt: number;
};

export type MediaResumablesState = Record<string, ResumeManifest>;

export type MediaSettings = {
  enableHlsMerging: boolean;
  maxHistory: number;
  // Optional filename template. When empty, the downloader falls back to deriveFileName.
  // Supported tokens: {title} {resolution} {ext} {kind} {host} {date}
  filenameTemplate: string;
  // How long a paused HTTP-range download stays resumable across browser
  // sessions before its OPFS scratch file gets GC'd. Days. Default 7.
  pausedDownloadRetentionDays: number;
};

export const DEFAULT_MEDIA_SETTINGS: MediaSettings = {
  enableHlsMerging: false,
  maxHistory: 30,
  filenameTemplate: '',
  pausedDownloadRetentionDays: 7,
};

export const MEDIA_MESSAGE = {
  DETECTED: 'media/detected',
  DOWNLOAD: 'media/download',
  CLEAR_TAB: 'media/clear-tab',
  CANCEL: 'media/cancel',
  CLEAR_DOWNLOADS: 'media/clear-downloads',
  MAIN_VIDEO_PRESENT: 'media/main-video-present',
  PASTE_URL: 'media/paste-url',
  PICKER_START: 'picker/start',
  PICKER_ACTIVATE: 'picker/activate',
  PICKER_PICKED: 'picker/picked',
  QUEUE_REORDER: 'media/queue-reorder',
  INTERCEPT_SHOW: 'media/intercept-show',
  INTERCEPT_DOWNLOAD_VIDSY: 'media/intercept-download-vidsy',
  INTERCEPT_RESUME_BROWSER: 'media/intercept-resume-browser',
  INTERCEPT_DISMISS: 'media/intercept-dismiss',
  RECORD_START: 'media/record-start',
  RECORD_STOP: 'media/record-stop',
  RECORD_PAUSE: 'media/record-pause',
  RECORD_RESUME: 'media/record-resume',
  // Content scripts read chrome.storage.session staler than extension pages, so
  // the content-UI pill pulls the authoritative download progress from the
  // background (which owns the writes) instead of reading storage directly.
  GET_DOWNLOADS: 'media/get-downloads',
  // SPA players (VK) don't expose the video title via <title>/og:title — the site
  // extractor relays the player's own title so network detections get a name.
  TITLE_HINT: 'media/title-hint',
  // Background → content script: push a tab's detection list directly. Content
  // scripts receive storage.onChanged unreliably, so the content-UI pill can
  // miss a detection that lands after it mounted (e.g. a live stream's manifest).
  DETECTIONS_PUSH: 'media/detections-push',
} as const;

export type MediaMessage =
  | { type: typeof MEDIA_MESSAGE.DETECTED; payload: Partial<MediaItem> & { url: string } }
  | {
      type: typeof MEDIA_MESSAGE.DOWNLOAD;
      payload: {
        url: string;
        key?: string; // progress tracking key (defaults to url); use item.url when downloading a variant
        kind?: MediaKind;
        fileName?: string;
        title?: string;
        tabId?: number;
        outputFormat?: 'mp4' | 'mp3';
        // When set, url is a video-only stream and audioUrl is its audio pair —
        // the download pipeline fetches both and muxes with FFmpeg -c copy.
        audioUrl?: string;
        audioMimeType?: string;
        // When kind === 'subtitle', this is the suggested format for the downloaded file (vtt/srt/…).
        subtitleFormat?: SubtitleFormat;
        // Optional language hint for subtitle filenames (e.g. 'en', 'pt-BR').
        subtitleLang?: string;
        item?: MediaItem; // full snapshot — persisted into progress state for the Downloads tab
      };
    }
  | { type: typeof MEDIA_MESSAGE.CLEAR_TAB; payload?: { tabId?: number } }
  | { type: typeof MEDIA_MESSAGE.CANCEL; payload: { url: string; intent?: 'pause' | 'cancel' } }
  | { type: typeof MEDIA_MESSAGE.CLEAR_DOWNLOADS; payload?: { keys?: string[] } }
  | { type: typeof MEDIA_MESSAGE.MAIN_VIDEO_PRESENT; payload: { present: boolean } }
  | { type: typeof MEDIA_MESSAGE.PASTE_URL; payload: { url: string; tabId?: number } }
  | { type: typeof MEDIA_MESSAGE.PICKER_START; payload?: { tabId?: number } }
  | { type: typeof MEDIA_MESSAGE.PICKER_ACTIVATE }
  | { type: typeof MEDIA_MESSAGE.PICKER_PICKED; payload: { url: string } }
  | { type: typeof MEDIA_MESSAGE.QUEUE_REORDER; payload: { key: string; direction: 'up' | 'down' } }
  | {
      type: typeof MEDIA_MESSAGE.INTERCEPT_SHOW;
      payload: {
        url: string;
        fileName?: string;
        mime?: string;
        fileSize?: number;
        referrer?: string;
      };
    }
  | { type: typeof MEDIA_MESSAGE.INTERCEPT_DOWNLOAD_VIDSY; payload: { url: string; fileName?: string } }
  | { type: typeof MEDIA_MESSAGE.INTERCEPT_RESUME_BROWSER; payload: { url: string; fileName?: string } }
  | { type: typeof MEDIA_MESSAGE.INTERCEPT_DISMISS; payload: { url: string } }
  | {
      type: typeof MEDIA_MESSAGE.RECORD_START;
      payload: {
        url: string;
        key?: string;
        kind?: MediaKind;
        fileName?: string;
        title?: string;
        tabId?: number;
        outputFormat?: 'mp4' | 'mp3';
        item?: MediaItem;
      };
    }
  | { type: typeof MEDIA_MESSAGE.RECORD_STOP; payload: { key: string; fileName?: string; discard?: boolean } }
  | { type: typeof MEDIA_MESSAGE.RECORD_PAUSE; payload: { key: string } }
  | { type: typeof MEDIA_MESSAGE.RECORD_RESUME; payload: { key: string } }
  | { type: typeof MEDIA_MESSAGE.GET_DOWNLOADS }
  | { type: typeof MEDIA_MESSAGE.TITLE_HINT; payload: { title: string } }
  | { type: typeof MEDIA_MESSAGE.DETECTIONS_PUSH; payload: { items: MediaItem[] } };

export type PasteUrlResult = { ok: true; kind: MediaKind } | { ok: false; error: string };
