export type MediaKind = 'video' | 'audio' | 'hls' | 'dash' | 'subtitle' | 'other';
export type MediaSource = 'element' | 'network';

export type SubtitleFormat = 'vtt' | 'srt' | 'ttml' | 'xml';

export type SubtitleTrack = {
  url: string;
  language: string; // BCP-47ish: 'en', 'es-419', 'pt-BR'
  label?: string; // human-readable: 'English', 'Spanish (Latin America)'
  format: SubtitleFormat;
  isAutoGenerated?: boolean;
};

export type MediaVariant = {
  url: string;
  name?: string;
  bandwidth?: number;
  resolution?: { width: number; height: number };
  codecs?: string;
  // Set when this variant is video-only and must be muxed with a separate audio track.
  // The downloader fetches both streams in parallel and merges them via FFmpeg -c copy.
  audioUrl?: string;
  audioMimeType?: string;
  // True when the manifest declared DRM key systems (Widevine/PlayReady/FairPlay).
  // The downloader cannot decrypt these streams — the UI disables the action.
  isDrmProtected?: boolean;
};

export type MediaItem = {
  id: string;
  url: string;
  kind: MediaKind;
  mimeType?: string;
  title?: string;
  pageUrl?: string;
  tabId?: number;
  detectedAt: number;
  source: MediaSource;
  fileName?: string;
  contentLength?: number;
  variants?: MediaVariant[];
  thumbnail?: string; // data URL or poster URL
  duration?: number; // seconds
  // Top-level audio pairing — used when the item itself (not a variant) is a
  // video-only stream that should be muxed with a separate audio track.
  audioUrl?: string;
  audioMimeType?: string;
  // Sidecar subtitle tracks attached to this video (YouTube captions, HLS/DASH text tracks).
  // Rendered as a language picker in the "More" menu.
  subtitles?: SubtitleTrack[];
  // True when any variant of this HLS/DASH manifest declared a DRM key system.
  // The downloader is intentionally DRM-blind — this flag just drives the UI lockout.
  isDrmProtected?: boolean;
};

export type MediaDownloadStage =
  | 'init'
  | 'fetch-manifest'
  | 'download-video'
  | 'download-audio'
  | 'mux'
  | 'finalize'
  | 'success'
  | 'failed'
  | 'cancelled'
  | 'paused';

export type MediaDownloadProgress = {
  key: string; // typically url
  stage: MediaDownloadStage;
  downloadedBytes: number;
  estimatedBytes?: number;
  muxPercent?: number;
  error?: string;
  downloadId?: number; // chrome.downloads ID for Play / Show in Folder
  item?: MediaItem; // snapshot of the source item — powers the Downloads tab and Retry
  outputFormat?: 'mp4' | 'mp3'; // remembered so Retry reuses the original choice
  startedAt?: number;
  updatedAt?: number;
};

export type MediaDownloadState = Record<string, MediaDownloadProgress>;

export type MediaHistoryItem = MediaItem & {
  downloadedAt: number;
  status: 'success' | 'failed';
  failureReason?: string;
  downloadId?: number; // chrome.downloads ID — used for Play / Show in Folder
};

export type MediaDetectionState = Record<string, MediaItem[]>;
export type MediaHistoryState = MediaHistoryItem[];

export type MediaSettings = {
  enableHlsMerging: boolean;
  maxHistory: number;
  // Optional filename template. When empty, the downloader falls back to deriveFileName.
  // Supported tokens: {title} {resolution} {ext} {kind} {host} {date}
  filenameTemplate: string;
};

export const DEFAULT_MEDIA_SETTINGS: MediaSettings = {
  enableHlsMerging: false,
  maxHistory: 30,
  filenameTemplate: '',
};

export const MEDIA_MESSAGE = {
  DETECTED: 'media/detected',
  DOWNLOAD: 'media/download',
  CLEAR_TAB: 'media/clear-tab',
  CANCEL: 'media/cancel',
  CLEAR_DOWNLOADS: 'media/clear-downloads',
  MAIN_VIDEO_PRESENT: 'media/main-video-present',
} as const;

export type MediaMessage =
  | { type: typeof MEDIA_MESSAGE.DETECTED; payload: Partial<MediaItem> & { url: string } }
  | {
      type: typeof MEDIA_MESSAGE.DOWNLOAD;
      payload: {
        url: string;
        key?: string; // progress tracking key (defaults to url); use item.url when downloading a variant
        kind?: MediaKind;
        fileName?: string;
        title?: string;
        tabId?: number;
        outputFormat?: 'mp4' | 'mp3';
        // When set, url is a video-only stream and audioUrl is its audio pair —
        // the download pipeline fetches both and muxes with FFmpeg -c copy.
        audioUrl?: string;
        audioMimeType?: string;
        // When kind === 'subtitle', this is the suggested format for the downloaded file (vtt/srt/…).
        subtitleFormat?: SubtitleFormat;
        // Optional language hint for subtitle filenames (e.g. 'en', 'pt-BR').
        subtitleLang?: string;
        item?: MediaItem; // full snapshot — persisted into progress state for the Downloads tab
      };
    }
  | { type: typeof MEDIA_MESSAGE.CLEAR_TAB; payload?: { tabId?: number } }
  | { type: typeof MEDIA_MESSAGE.CANCEL; payload: { url: string; intent?: 'pause' | 'cancel' } }
  | { type: typeof MEDIA_MESSAGE.CLEAR_DOWNLOADS; payload?: { keys?: string[] } }
  | { type: typeof MEDIA_MESSAGE.MAIN_VIDEO_PRESENT; payload: { present: boolean } };
